### PR TITLE
add support from clip board

### PR DESCRIPTION
**Pull request by im6h**

### CODE REVIEW

**Review by ducphamle2 — APPROVED** [review]
lgtm

**Comment by ducphamle2** [comment]
@im6h can you add a new commit that increases the extension version? I forgot abt that

**Comment by im6h** [comment]
> reases the extension version? I forgot

sorry guys, this feature still doesn't work on macos. Maybe you need to revert the commit?

**Comment by ducphamle2** [comment]
Sure, lets revert it. I cant test it either because im not using mac

**Pull request merged**
